AUTH0_CLIENT_ID = 'lrRTRBboOlqLVLYxSCtmN3mT07oUtRuC'
AUTH0_CLIENT_SECRET = 'pgcQuqIfd3FppUja8u2O92yNV4rTS6OAwoXn8RXFh-KiNEVgXR3-gKGk9CDcNROp'
AUTH0_DOMAIN = 'lawrencep.us.auth0.com'
AUTH0_AUDIENCE = 'agency'
ALGORITHMS = ['RS256']
